import type { Metadata } from "next"
import { Figtree, Geist, Geist_Mono, Nunito_Sans } from "next/font/google"

import { cn } from "@/lib/utils"

import "./globals.css"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] })
const nunitoSans = Nunito_Sans({ subsets: ["latin"], variable: "--font-sans" })
const figtreeHeading = Figtree({ subsets: ["latin"], variable: "--font-heading" })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        nunitoSans.variable,
        figtreeHeading.variable
      )}
    >
      <body className="flex min-h-full flex-col">{children}</body>
    </html>
  )
}
